### ISSUE TITLE
你好， 你在v2ex是不是提问过vuex处理超大表单问题？

### ISSUE THREAD

**Issue by io-o** [leafiy/gelatin-ui#3]
![image](https://user-images.githubusercontent.com/22197685/52534808-1a7de480-2d81-11e9-867f-8b9e9d1b6cdd.png)
如果是你的话，想问下你的解决方案哈，非常感谢！！！  不是的话，不好意思，打扰了。

**Comment by leafiy** [comment]
@Kevinl7 是我提的，最终的解决方案就在此项目的packages/v 中，文档在https://gelatin-ui.leafiy.com/v/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%AA%8C%E8%AF%81%E8%A7%84%E5%88%99

只要把需要验证的每个input/textarea 包含在 V 组件中，调用一个validate方法就可以了
这是我能想到最简单的办法了，如果有新的方法欢迎提出啊

**Comment by io-o** [comment]
感谢，你没有把form表单的所有字段放到vuex里， 想问下是怎么考虑的？
我遇到的问题是， 大概60多个字段，分了两个组件（字段包含 string, array，number）分两步填写（验证的话分步验证好？还是统一验证好？）， 如果不使用vuex的话，获取组件的数据比较麻烦， 需要使用eventBus传递， 使用vuex的话，按照文档的写法，不能使用v-model , 在 computed里 使用 get set ， 感觉也挺麻烦的， 想问下，你有什么好解决方案么？  谢谢！！！

**Comment by leafiy** [comment]
@Kevinl7 我最初也是放在vuex中，踩了几个坑，由于不能监控object变化只能使用array或每个字段有单独的set/get，导致store.js本身就不会好看。array的话大概50个字段后就能感受到有处理时间，而且项目运行的终端性能都很差也放弃了。
然后采用每个字段单独写，但是随着项目进展，后期每增加一个字段，同时要写一个规则和至少3个store方法，工作量至少增加一倍。
之后我也尝试过event bus，同样要写很多无关的emit/on，也就放弃了。

最后，从整体入手，把每一个input都独立为一个组件，在统一到一个或多个大组件中，这样大组件之中的所有input都可以共享状态了，每个大组件之间也可以使用内置methods手动共享状态，问题解决。

最后统一验证和分布验证我是直接写在验证规则里面了，统一的就直接用同步方法，异步的直接用promise，也就不用考虑统一还是分布的问题了。

只是我项目中的经验，不一定适用所有的情景。

**Comment by io-o** [comment]
好的，非常感谢！！！ 感觉你这种解决方案应该是目前最简单有效的了。
